version: '3'
services:
  polybot:
    image: tamer153/polybot:2.2
    container_name: polybot
    ports:
      - "8443:8443"
    environment:
      - BUCKET_NAME=${BUCKET_NAME}
      - TELEGRAM_TOKEN=${TELEGRAM_TOKEN_FILE}
      - TELEGRAM_APP_URL=https://certain-wombat-fairly.ngrok-free.app
    secrets:
      - my_secret
    depends_on:
      - ngrok
    volumes:
      - C:\Users\failc\.aws:/root/.aws
    networks:
    - mongo-network

  ngrok:
    image: ngrok/ngrok:latest
    container_name: ngrok
    environment:
      - NGROK_AUTHTOKEN=${NGROK_AUTHTOKEN}
    command: ["http", "--domain=${domain}", "polybot:8443"]
    secrets:
      - my_secret
    networks:
      - mongo-network

networks:
  mongo-network:
    driver: bridge

secrets:
  my_secret:
    file: .env

